services:

  techdocs-builder-builder:
    container_name: techdocs-builder-builder
    image: webgrip/techdocs-builder:latest
    pull_policy: never
    build:
      context: .
      dockerfile: ops/docker/techdocs-builder/Dockerfile

  builder-mkdocs-runner:
    container_name: builder-mkdocs-runner
    image: webgrip/mkdocs-runner:latest@sha256:86c382e885a4c71837bebe7b56a8ce779415cc21ab4b1c4c931d4ff891106af8
    pull_policy: always
    depends_on:
      techdocs-builder-builder:
        condition: service_completed_successfully
    ports:
      - "8000:8000"
    volumes:
      - ./docs/mkdocs:/docs

  builder-techdocs-runner:
    container_name: techdocs-builder-techdocs
    image: webgrip/techdocs-runner:latest@sha256:715d423dd6a563fbdc3f97298dde8d96374f3e22bafc08966f623e2445bdb7cf
    pull_policy: always
    depends_on:
      techdocs-builder-builder:
        condition: service_completed_successfully
    ports:
      - "8001:8000"
    volumes:
      - ./docs/techdocs:/docs
